wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1672646180
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 2
      - 13
      - 16
      4: 3.9.6
      5: 0.12.18
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 256
buffer_size:
  desc: null
  value: 100000
cql_weight:
  desc: null
  value: 1.0
env:
  desc: null
  value: Pendulum-v1
episodes:
  desc: null
  value: 300
eval_every:
  desc: null
  value: 1
hidden_size:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 0.0003
log_video:
  desc: null
  value: 0
run_name:
  desc: null
  value: CQL-SAC
save_every:
  desc: null
  value: 100
seed:
  desc: null
  value: 1
target_action_gap:
  desc: null
  value: 10
tau:
  desc: null
  value: 0.005
temperature:
  desc: null
  value: 1.0
with_lagrange:
  desc: null
  value: 0
